// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObligatorioApiario.Data;

#nullable disable

namespace ObligatorioApiario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629230333_InitialCreatePostgres")]
    partial class InitialCreatePostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObligatorioApiario.Models.Apiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Apiarios");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Colmena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioReina")
                        .HasColumnType("integer");

                    b.Property<int>("ApiarioId")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadAbejas")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadMarcos")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoSalud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInstalacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("TipoAbeja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.ToTable("Colmenas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Cosecha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.ToTable("Cosechas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.CosechaColmena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ColmenaId")
                        .HasColumnType("integer");

                    b.Property<int>("CosechaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColmenaId");

                    b.HasIndex("CosechaId");

                    b.ToTable("CosechasColmenas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ClimaEstado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClimaTemperatura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ColmenaId")
                        .HasColumnType("integer");

                    b.Property<string>("ColmenasRiesgo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HerramientasRequeridas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NivelPrioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreApiario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotasCampo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiarioId");

                    b.HasIndex("ColmenaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Colmena", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apiario", "Apiario")
                        .WithMany("Colmenas")
                        .HasForeignKey("ApiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Cosecha", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apiario", "Apiario")
                        .WithMany("Cosechas")
                        .HasForeignKey("ApiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.CosechaColmena", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Colmena", "Colmena")
                        .WithMany("HistorialCosechas")
                        .HasForeignKey("ColmenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ObligatorioApiario.Models.Cosecha", "Cosecha")
                        .WithMany("Detalles")
                        .HasForeignKey("CosechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmena");

                    b.Navigation("Cosecha");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Tarea", b =>
                {
                    b.HasOne("ObligatorioApiario.Models.Apiario", null)
                        .WithMany("Tareas")
                        .HasForeignKey("ApiarioId");

                    b.HasOne("ObligatorioApiario.Models.Colmena", "Colmena")
                        .WithMany()
                        .HasForeignKey("ColmenaId");

                    b.Navigation("Colmena");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Apiario", b =>
                {
                    b.Navigation("Colmenas");

                    b.Navigation("Cosechas");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Colmena", b =>
                {
                    b.Navigation("HistorialCosechas");
                });

            modelBuilder.Entity("ObligatorioApiario.Models.Cosecha", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
